asl 4574 named person training record
UKHomeOffice/asl-pages pull request #1652
Opened 2024-11-19 17:38 UTC by parvinba

2024-11-19 18:05 UTC, jeff-horton-ho-sas requested changes
Looks good - some changes to fit in with other parts of the code base.

Let me know if you want a quick chat about how content objects/`<Snippet>` works?

2024-11-19 18:05 UTC, jeff-horton-ho-sas commented on pages/profile/read/views/index.jsx
> +            <p>{instruction[1]}</p>
```suggestion
            <Snippet>instruction</Snippet>
```

2024-11-19 18:05 UTC, jeff-horton-ho-sas commented on pages/training/dashboard/views/index.jsx
> +      <p>{instruction[1]}</p>
```suggestion
      <Snippet>instruction</Snippet>
```

2024-11-20 09:42 UTC, parvinba commented on pages/training/dashboard/content/index.js
> +    'You should not request an exemption for incomplete training as you still need to complete it.'],
done

2024-11-20 09:47 UTC, parvinba commented on pages/profile/read/views/index.jsx
> +            <p>{instruction[1]}</p>
done

2024-11-20 09:50 UTC, parvinba commented
@jeff-horton-ho-sas  - All suggestions were implemented, please rereview

2024-11-20 16:31 UTC, merged